In [ ]:
import os,glob,re
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import math
from shapely import wkt
import geopandas as gpd
from shapely.ops import unary_union
from lxml import etree
from pykml.factory import KML_ElementMaker as KML
import folium
import folium.plugins
import unicodedata
import dimsim
from datetime import datetime, timedelta
import openpyxl

In [2]:
def extractYZPZ(df):
    '''
    提取养殖品种
    '''
    print("check df.index:")
    print(f"总长{len(df)},最大索引{df.index.max()}")
    yzxx = df['养殖品种/预计亩产量'].str.replace('斤/亩','')
    yzxx = yzxx.str.split('，',expand=True)
    yzxx = yzxx.fillna('/')
    yzpz = pd.DataFrame(columns=yzxx.columns,index=yzxx.index)
    mcl = pd.DataFrame(columns=yzxx.columns,index=yzxx.index)
    print(f"养殖品种、亩产量拆分")
    for c in yzxx.columns:
        idx = yzxx[c]!='/'
        yzpz.loc[idx,c] = yzxx.loc[idx,c].str.split(':',expand=True)[0]
        mcl.loc[idx,c] = yzxx.loc[idx,c].str.split(':',expand=True)[1]
    
    yzpz = yzpz.fillna('/')
    mcl = mcl.fillna(0)
    mcl = mcl.to_numpy().astype('float')
    yzpz_unq = np.unique(yzpz.to_numpy())
    n = yzpz_unq.shape[0]-1
    print(f"共{n}个品种")
    for i,pz in enumerate(yzpz_unq[yzpz_unq!='/']):
        print(f"{i+1}/{n}:{pz}")
        pz_idx = np.argwhere(yzpz==pz)
        print(pz_idx)
        df.loc[df.index[pz_idx[:,0]],f'{pz}亩产量(斤/亩)'] = mcl[yzpz==pz]

    df['总产量(斤/亩)']=df[df.columns[0-n:]].sum(axis=1)
    df['养殖品种数量']=(df[df.columns[-1-n:-1]] >= 0).sum(axis=1)
    return df,yzpz_unq

In [3]:
# ===== 构建匹配键 =====
def make_key(df):
    return df[["养殖经营人名称", "联系方式", "身份证号", "统一社会信用代码", "地址"]].astype(str).agg("-".join, axis=1)

### 1、统计所有主体数量和清单

In [3]:
# rawpath = r'E:\江苏省养殖池塘上图入库项目\填报数据统计\13个县4条鱼主体统计\丹阳4月9日'
# os.chdir(rawpath)
# # df_mcl=pd.read_excel('高邮市0704.xlsx')
# df_mcl=pd.read_excel('丹阳市.xlsx')#,skiprows=1

In [4]:
# df=df_mcl.copy()

In [5]:
# # 按指定字段划分主体并统计数据
# result = df_mcl.groupby(['养殖经营人名称','身份证号','统一社会信用代码','联系方式','地址']).agg({
#     "养殖经营人名称": "first",
#     "联系方式": "first",
#     "身份证号": "first",
#     "统一社会信用代码": "first",
#     "地址": "first",
#     '图斑编号':list
#     })

In [6]:
# # 获取地址信息，并定义统计层级
# address=result['地址'].str.split('-',expand=True)
# address['区镇']=address[2]+'-'+address[3]
# address_unq=np.unique(address['区镇'].tolist())
# address_unq

In [7]:
# # 创建统计表
# row_index=address_unq
# column_index=['合计']
# result_tj = pd.DataFrame(index=row_index, columns=column_index)

In [8]:
# # 筛选统计数据
# for j in address_unq:
#     for i in ['合计']:
#         if i == '合计':
#             idx3=result['地址'].str.contains(j)
#             result_tj.loc[j,i]=len(result[idx3])

In [9]:
# # 主体清单导出
# result_tj.to_excel(os.path.join("丹阳各镇总主体数量test.xlsx"))
# result.to_excel(os.path.join("丹阳主体_总test.xlsx"))

### 2、统计特定条件主体数量

In [854]:
rawpath = r'E:\江苏省养殖池塘上图入库项目\填报数据统计\13个县4条鱼主体统计\7月新\0717建湖'
os.chdir(rawpath)
df_mcl=pd.read_excel('建湖0717.xlsx')
# df_mcl=pd.read_excel('金湖县0409.xlsx')#,skiprows=1

In [855]:
idx2=df_mcl['图斑面积']!='/'
idx22=df_mcl['图斑面积']=='/'
df_mcl['面积_亩']=''
df_mcl.loc[idx2,'面积_亩']=df_mcl.loc[idx2,'图斑面积'].astype(float)*0.0015
# df_mcl.loc[idx22,'面积_亩']=0.001

In [856]:
# 提取成品养殖、有面积的数据
# idx1=df_mcl['用途'].str.contains('成品养殖')|df_mcl['用途'].str.contains('苗种培育')
idx1=df_mcl['用途'].str.contains('成品养殖')
idx2=df_mcl['图斑面积']!='/'
idx=idx1&idx2
df=df_mcl[idx].copy()

In [104]:
# idx2=df_mcl['图斑面积']!='/'
# df=df_mcl[idx2].copy()

In [857]:
# 按指定字段划分原始信息表中主体并统计数据
df_z=df_mcl.copy()
result_z = df_z.groupby(['养殖经营人名称','身份证号','统一社会信用代码','联系方式','地址']).agg({
    "养殖经营人名称": "first",
    "联系方式": "first",
    "身份证号": "first",
    "统一社会信用代码": "first",
    "地址": "first",
    '图斑编号':list,
    })

In [595]:
# 按指定字段划分成品养殖且有面积数据的主体并统计数据
result_z = df.groupby(['养殖经营人名称','身份证号','统一社会信用代码','联系方式','地址']).agg({
    "养殖经营人名称": "first",
    "联系方式": "first",
    "身份证号": "first",
    "统一社会信用代码": "first",
    "地址": "first",
    '图斑编号':list,
    '面积_亩':"sum"
    })

result_z.to_excel(os.path.join("无锡常州鳊鱼主体0710_总.xlsx"))

In [858]:
# 区分淡海水品种
npz = ['其他种类','南美白对虾','螺','鲈鱼']

for p in npz:
        idx0 = df['养殖品种/预计亩产量'].str.contains(p)
        if len(df.loc[idx0,'水体类型'])>0:
            stlx = df.loc[idx0,'水体类型'].unique()
            for s in stlx[stlx!='/']:
                idx = (df['水体类型']==s) & (idx0)
                df.loc[idx,'养殖品种/预计亩产量'] = df.loc[idx,'养殖品种/预计亩产量'].str.replace(p,f"{s}{p}")

In [859]:
# 提取各品种亩产量
df,yzpz_unq= extractYZPZ(df)

check df.index:
总长4582,最大索引4838
养殖品种、亩产量拆分
共20个品种
1/20:乌鳢
[[  86    0]
 [1254    0]
 [1320    0]
 [1560    0]
 [1561    0]
 [1562    0]
 [1563    0]
 [1564    0]
 [1631    0]
 [1632    0]
 [1633    0]
 [1634    0]
 [1635    0]
 [1636    0]
 [1645    0]
 [1646    0]
 [1649    0]
 [1988    1]
 [1989    1]
 [1990    1]
 [1991    1]
 [1992    1]
 [2276    0]
 [2277    0]
 [2278    0]
 [2279    0]
 [2280    0]
 [2281    0]
 [2282    0]
 [2447    1]
 [2448    1]
 [2543    2]
 [2544    2]
 [2545    2]
 [2546    2]
 [2547    2]
 [2548    2]
 [2549    2]
 [2550    2]
 [3333    1]
 [3334    0]
 [3335    0]
 [3420    0]
 [3421    0]
 [3422    0]
 [3423    0]
 [3424    0]
 [3425    0]
 [3426    0]
 [3427    0]
 [3428    0]
 [3429    0]
 [3430    0]
 [3748    0]
 [3929    0]
 [4533    0]
 [4534    0]
 [4535    0]
 [4536    0]
 [4537    0]
 [4538    0]
 [4539    0]
 [4540    0]
 [4541    0]
 [4542    0]
 [4551    0]
 [4552    0]
 [4553    0]]
2/20:克氏原螯虾
[[ 113    1]
 [ 124    0]
 [ 125    0]
 [ 126    0]
 [ 127    0]
 [ 128    0]
 [ 130    0]
 [ 140    0]
 [ 358    0]
 [ 359    0]
 [ 460    0]
 [ 502    0]
 [ 503    0]
 [ 504    0]
 [ 505    0]
 [ 889    0]
 [ 891    0]
 [ 892    0]
 [ 893    0]
 [ 897    0]
 [ 898    0]
 [ 899    0]
 [ 900    0]
 [ 901    0]
 [ 940    0]
 [ 941    0]
 [ 942    0]
 [ 999    0]
 [1412    0]
 [1760    0]
 [1762    0]
 [2005    0]
 [2742    0]
 [2743    0]
 [2744    0]
 [2745    0]
 [2746    0]
 [2747    0]
 [2748    0]
 [2749    0]
 [2750    0]
 [2751    0]
 [2752    0]
 [2770    0]
 [2771    0]
 [2772    0]
 [2773    0]
 [2774    0]
 [2775    0]
 [2776    0]
 [2777    0]
 [2778    0]
 [2805    0]
 [2806    0]
 [2807    0]
 [2808    0]
 [2809    0]
 [2810    0]
 [2811    0]
 [2812    0]
 [2813    0]
 [2814    0]
 [2815    0]
 [2816    0]
 [2817    0]
 [2818    0]
 [2819    0]
 [2821    0]
 [2822    0]
 [2823    0]
 [2824    0]
 [2825    0]
 [2826    0]
 [2856    0]
 [2875    0]
 [2974    0]
 [3135    0]
 [3136    0]
 [3137    0]
 [3918    0]
 [3935    0]
 [3960    0]
 [3961    0]]
3/20:其他种类
[[314   0]]
4/20:河蚌
[[2003    0]]
5/20:河蟹
[[   1    0]
 [   2    0]
 [   4    0]
 ...
 [4511    0]
 [4512    0]
 [4513    0]]
6/20:淡水其他种类
[[ 815    0]
 [ 820    0]
 [1195    0]
 [1196    0]
 [1219    0]
 [1255    0]
 [1256    0]
 [1257    0]
 [1258    0]
 [1259    0]
 [1260    0]
 [1261    0]
 [1266    0]
 [1268    0]
 [1271    0]
 [1276    0]
 [1315    0]
 [1752    0]
 [1753    0]
 [1754    0]
 [1755    0]
 [1756    0]
 [1757    0]
 [1758    0]
 [1765    0]
 [1917    0]
 [2291    0]
 [2292    0]
 [2311    0]
 [2312    0]
 [2313    0]
 [2314    0]
 [2315    0]
 [2316    0]
 [2317    0]
 [2320    0]
 [2321    0]
 [2322    0]
 [2334    0]
 [2428    0]
 [2429    0]
 [2430    0]
 [2733    0]
 [2734    0]
 [2735    0]
 [2736    0]
 [2737    0]
 [2738    0]
 [2739    0]
 [2740    0]
 [2741    0]
 [2749    1]
 [2751    1]
 [2752    1]
 [2773    1]
 [2775    1]
 [2776    1]
 [2777    1]
 [2778    1]
 [2805    1]
 [2806    1]
 [2807    1]
 [2808    1]
 [2809    1]
 [2810    1]
 [2811    1]
 [2812    1]
 [2813    1]
 [2814    1]
 [2815    1]
 [2816    1]
 [2817    1]
 [2818    1]
 [2819    1]
 [2821    1]
 [2822    1]
 [2823    1]
 [2824    1]
 [2825    1]
 [2826    1]
 [2974    1]
 [3458    0]
 [3459    0]
 [3918    1]
 [4502    2]]
7/20:淡水南美白对虾
[[ 118    0]
 [ 119    0]
 [ 121    0]
 [ 122    0]
 [ 270    0]
 [ 276    0]
 [ 382    0]
 [ 383    0]
 [ 384    0]
 [ 385    0]
 [ 386    0]
 [ 387    0]
 [ 388    0]
 [ 429    1]
 [ 430    1]
 [ 431    1]
 [ 432    1]
 [ 433    1]
 [ 798    0]
 [ 799    0]
 [ 800    0]
 [ 801    0]
 [ 802    0]
 [ 803    0]
 [ 804    0]
 [ 805    0]
 [ 806    0]
 [ 807    0]
 [ 808    0]
 [ 809    0]
 [ 810    0]
 [ 811    0]
 [1226    1]
 [1231    0]
 [1232    0]
 [1272    0]
 [1273    0]
 [1274    0]
 [1275    0]
 [1322    3]
 [1324    3]
 [1325    3]
 [1327    3]
 [1486    3]
 [1487    3]
 [1489    0]
 [1537    3]
 [1538    3]
 [1539    3]
 [1560    1]
 [1561    1]
 [1562    1]
 [1563    1]
 [1564    1]
 [1626    1]
 [1627    1]
 [1628    1]
 [1638    2]
 [1642    2]
 [1643    2]
 [1644    2]
 [1650    2]
 [1651    2]
 [1652    2]
 [1653    2]
 [1654    1]
 [1679    0]
 [1680    0]
 [1797    1]
 [1798    1]
 [1799    1]
 [1801    1]
 [1817    1]
 [1826    3]
 [1827    3]
 [1828    3]
 [1833    3]
 [1834    3]
 [1835    3]
 [1836    3]
 [1914    1]
 [1915    1]
 [1916    1]
 [1935    1]
 [2043    0]
 [2044    0]
 [2065    0]
 [2066    0]
 [2067    0]
 [2068    0]
 [2136    0]
 [2137    0]
 [2138    0]
 [2139    0]
 [2140    0]
 [2141    0]
 [2142    0]
 [2143    0]
 [2144    0]
 [2145    0]
 [2146    0]
 [2147    0]
 [2148    0]
 [2149    0]
 [2150    0]
 [2151    0]
 [2155    0]
 [2165    0]
 [2166    0]
 [2169    0]
 [2170    0]
 [2171    0]
 [2213    0]
 [2214    0]
 [2215    0]
 [2218    0]
 [2220    0]
 [2221    0]
 [2222    0]
 [2223    0]
 [2224    0]
 [2225    0]
 [2226    0]
 [2227    0]
 [2228    0]
 [2229    0]
 [2230    0]
 [2231    0]
 [2232    0]
 [2233    0]
 [2234    0]
 [2235    0]
 [2236    0]
 [2237    0]
 [2238    0]
 [2239    0]
 [2249    1]
 [2259    0]
 [2318    1]
 [2319    1]
 [2323    0]
 [2324    0]
 [2325    0]
 [2326    0]
 [2327    0]
 [2328    0]
 [2329    0]
 [2330    0]
 [2331    1]
 [2408    1]
 [2409    1]
 [2410    1]
 [2411    1]
 [2412    1]
 [2413    1]
 [2414    1]
 [2415    1]
 [2416    1]
 [2417    1]
 [2419    1]
 [2420    1]
 [2421    1]
 [2422    1]
 [2423    1]
 [2424    1]
 [2425    1]
 [2426    1]
 [2427    1]
 [2431    1]
 [2432    1]
 [2433    1]
 [2434    1]
 [2435    1]
 [2436    1]
 [2437    1]
 [2438    1]
 [2439    1]
 [2440    1]
 [2441    1]
 [2442    1]
 [2443    1]
 [2444    1]
 [2445    1]
 [2446    1]
 [2529    2]
 [2532    2]
 [2536    2]
 [2537    2]
 [2538    2]
 [2539    2]
 [2552    2]
 [2553    2]
 [2554    2]
 [2555    2]
 [2556    2]
 [2557    2]
 [2558    2]
 [2559    2]
 [2569    2]
 [2570    2]
 [2572    2]
 [2573    2]
 [2574    2]
 [2575    2]
 [2576    2]
 [2577    2]
 [2578    2]
 [2579    2]
 [2580    2]
 [2581    2]
 [2582    2]
 [2583    2]
 [2584    2]
 [2585    2]
 [2586    2]
 [2587    2]
 [2588    2]
 [2589    2]
 [2590    2]
 [2591    2]
 [2592    2]
 [2593    2]
 [2594    2]
 [2595    2]
 [2596    2]
 [2597    2]
 [2598    2]
 [2599    2]
 [2600    2]
 [2601    2]
 [2603    2]
 [2604    2]
 [2605    2]
 [2606    2]
 [2607    2]
 [2608    2]
 [2609    2]
 [2610    2]
 [2611    2]
 [2612    2]
 [2613    2]
 [2614    2]
 [2615    2]
 [2616    2]
 [2617    2]
 [2618    2]
 [2619    2]
 [2620    2]
 [2621    2]
 [2629    0]
 [2630    0]
 [2631    0]
 [2632    0]
 [2633    0]
 [2634    0]
 [2635    0]
 [2637    0]
 [2638    0]
 [2639    0]
 [2640    0]
 [2641    0]
 [2642    0]
 [2643    0]
 [2644    0]
 [2645    0]
 [2646    0]
 [2647    0]
 [2648    0]
 [2649    0]
 [2650    0]
 [2651    0]
 [2652    0]
 [2653    0]
 [2654    0]
 [2655    0]
 [2656    0]
 [2657    0]
 [2658    0]
 [2659    0]
 [2660    0]
 [2661    0]
 [2662    0]
 [2663    0]
 [2664    0]
 [2665    0]
 [2666    0]
 [2667    0]
 [2668    0]
 [2669    0]
 [2670    0]
 [2671    0]
 [2672    0]
 [2673    0]
 [2674    0]
 [2675    0]
 [2676    0]
 [2677    0]
 [2678    0]
 [2679    0]
 [2680    0]
 [2681    0]
 [2682    0]
 [2683    0]
 [2684    0]
 [2687    1]
 [2688    1]
 [2692    1]
 [2693    1]
 [2694    1]
 [2703    1]
 [2704    0]
 [2705    0]
 [2706    0]
 [2707    0]
 [2708    0]
 [2709    0]
 [2710    0]
 [2711    0]
 [2712    0]
 [2713    0]
 [2716    0]
 [2717    0]
 [2718    0]
 [2719    0]
 [2720    0]
 [2721    0]
 [2722    0]
 [2723    0]
 [2724    0]
 [2725    0]
 [2727    0]
 [2728    0]
 [2729    0]
 [2730    0]
 [2731    0]
 [3139    2]
 [3140    2]
 [3141    2]
 [3142    2]
 [3143    2]
 [3144    2]
 [3145    2]
 [3146    2]
 [3147    2]
 [3148    2]
 [3319    0]
 [3320    0]
 [3321    0]
 [3322    0]
 [3744    0]
 [3745    0]
 [3746    0]
 [3762    0]
 [3764    0]
 [3765    0]
 [3770    0]
 [3771    0]
 [3772    0]
 [3773    0]
 [3774    0]
 [3775    0]
 [3776    0]
 [3778    0]
 [4499    0]]
8/20:罗氏沼虾
[[  27    0]
 [ 411    0]
 [ 429    0]
 [ 430    0]
 [ 431    0]
 [ 432    0]
 [ 433    0]
 [ 491    0]
 [ 492    0]
 [ 493    0]
 [ 494    0]
 [ 495    0]
 [ 496    0]
 [ 497    0]
 [ 498    0]
 [ 499    0]
 [ 500    0]
 [ 501    0]
 [ 833    0]
 [1002    0]
 [1214    0]
 [1218    0]
 [1220    0]
 [1223    0]
 [1224    0]
 [1225    0]
 [1226    0]
 [1234    0]
 [1235    0]
 [1269    0]
 [1270    0]
 [1277    0]
 [1281    0]
 [1322    2]
 [1324    2]
 [1325    2]
 [1327    2]
 [1486    2]
 [1487    2]
 [1506    0]
 [1507    0]
 [1508    0]
 [1509    0]
 [1510    0]
 [1511    0]
 [1512    0]
 [1513    0]
 [1514    0]
 [1515    0]
 [1516    0]
 [1517    0]
 [1518    0]
 [1519    0]
 [1520    0]
 [1521    0]
 [1522    0]
 [1523    0]
 [1524    0]
 [1525    0]
 [1526    0]
 [1527    0]
 [1528    0]
 [1529    0]
 [1530    0]
 [1531    0]
 [1532    0]
 [1537    2]
 [1538    2]
 [1539    2]
 [1571    0]
 [1572    0]
 [1573    0]
 [1574    0]
 [1575    0]
 [1576    0]
 [1577    0]
 [1578    0]
 [1581    0]
 [1582    0]
 [1584    0]
 [1585    0]
 [1586    0]
 [1587    0]
 [1588    0]
 [1589    0]
 [1590    0]
 [1591    0]
 [1592    0]
 [1593    0]
 [1594    0]
 [1595    0]
 [1596    0]
 [1597    0]
 [1598    0]
 [1599    0]
 [1600    0]
 [1601    0]
 [1602    0]
 [1603    0]
 [1604    0]
 [1605    0]
 [1606    0]
 [1607    0]
 [1622    0]
 [1626    0]
 [1627    0]
 [1628    0]
 [1637    0]
 [1638    1]
 [1639    0]
 [1642    1]
 [1643    1]
 [1644    1]
 [1650    1]
 [1651    1]
 [1652    1]
 [1653    1]
 [1654    0]
 [1655    0]
 [1656    0]
 [1657    0]
 [1658    0]
 [1659    0]
 [1660    0]
 [1661    0]
 [1662    0]
 [1663    0]
 [1664    0]
 [1665    0]
 [1666    0]
 [1667    0]
 [1668    0]
 [1669    0]
 [1670    0]
 [1671    0]
 [1672    0]
 [1673    0]
 [1675    0]
 [1676    0]
 [1677    0]
 [1678    0]
 [1681    0]
 [1682    0]
 [1683    0]
 [1684    0]
 [1685    0]
 [1686    0]
 [1687    0]
 [1688    0]
 [1689    0]
 [1690    0]
 [1691    0]
 [1692    0]
 [1693    0]
 [1694    0]
 [1695    0]
 [1696    0]
 [1697    0]
 [1698    0]
 [1699    0]
 [1700    0]
 [1701    0]
 [1702    0]
 [1703    0]
 [1704    0]
 [1705    0]
 [1706    0]
 [1707    0]
 [1708    0]
 [1709    0]
 [1710    0]
 [1711    0]
 [1712    0]
 [1713    0]
 [1714    0]
 [1715    0]
 [1716    0]
 [1717    0]
 [1718    0]
 [1719    0]
 [1720    0]
 [1721    0]
 [1722    0]
 [1723    0]
 [1724    0]
 [1725    0]
 [1726    0]
 [1727    0]
 [1728    0]
 [1729    0]
 [1730    0]
 [1731    0]
 [1732    0]
 [1733    0]
 [1734    0]
 [1735    0]
 [1736    0]
 [1740    0]
 [1741    0]
 [1742    0]
 [1743    0]
 [1744    0]
 [1745    0]
 [1746    0]
 [1747    0]
 [1748    0]
 [1749    0]
 [1750    0]
 [1751    0]
 [1791    0]
 [1797    0]
 [1798    0]
 [1799    0]
 [1801    0]
 [1804    0]
 [1805    0]
 [1806    0]
 [1807    0]
 [1817    0]
 [1826    2]
 [1827    2]
 [1828    2]
 [1829    0]
 [1833    2]
 [1834    2]
 [1835    2]
 [1836    2]
 [1837    0]
 [1838    0]
 [1850    0]
 [1851    0]
 [1852    0]
 [1853    0]
 [1888    0]
 [1889    0]
 [1890    0]
 [1892    0]
 [1893    0]
 [1904    0]
 [1905    0]
 [1906    0]
 [1907    0]
 [1908    0]
 [1909    0]
 [1910    0]
 [1911    0]
 [1914    0]
 [1915    0]
 [1916    0]
 [1935    0]
 [2016    0]
 [2017    0]
 [2018    0]
 [2080    0]
 [2081    0]
 [2082    0]
 [2083    0]
 [2084    0]
 [2085    0]
 [2086    0]
 [2087    0]
 [2249    0]
 [2306    0]
 [2318    0]
 [2319    0]
 [2331    0]
 [2408    0]
 [2409    0]
 [2410    0]
 [2411    0]
 [2412    0]
 [2413    0]
 [2414    0]
 [2415    0]
 [2416    0]
 [2417    0]
 [2419    0]
 [2420    0]
 [2421    0]
 [2422    0]
 [2423    0]
 [2424    0]
 [2425    0]
 [2426    0]
 [2427    0]
 [2431    0]
 [2432    0]
 [2433    0]
 [2434    0]
 [2435    0]
 [2436    0]
 [2437    0]
 [2438    0]
 [2439    0]
 [2440    0]
 [2441    0]
 [2442    0]
 [2443    0]
 [2444    0]
 [2445    0]
 [2446    0]
 [2529    1]
 [2532    1]
 [2536    1]
 [2537    1]
 [2538    1]
 [2539    1]
 [2552    1]
 [2553    1]
 [2554    1]
 [2555    1]
 [2556    1]
 [2557    1]
 [2558    1]
 [2559    1]
 [2568    0]
 [2569    1]
 [2570    1]
 [2572    1]
 [2573    1]
 [2574    1]
 [2575    1]
 [2576    1]
 [2577    1]
 [2578    1]
 [2579    1]
 [2580    1]
 [2581    1]
 [2582    1]
 [2583    1]
 [2584    1]
 [2585    1]
 [2586    1]
 [2587    1]
 [2588    1]
 [2589    1]
 [2590    1]
 [2591    1]
 [2592    1]
 [2593    1]
 [2594    1]
 [2595    1]
 [2596    1]
 [2597    1]
 [2598    1]
 [2599    1]
 [2600    1]
 [2601    1]
 [2603    1]
 [2604    1]
 [2605    1]
 [2606    1]
 [2607    1]
 [2608    1]
 [2609    1]
 [2610    1]
 [2611    1]
 [2612    1]
 [2613    1]
 [2614    1]
 [2615    1]
 [2616    1]
 [2617    1]
 [2618    1]
 [2619    1]
 [2620    1]
 [2621    1]
 [2687    0]
 [2688    0]
 [2692    0]
 [2693    0]
 [2694    0]
 [2696    0]
 [2697    0]
 [2698    0]
 [2700    0]
 [2703    0]
 [3129    0]
 [3130    0]
 [3138    0]
 [3139    1]
 [3140    1]
 [3141    1]
 [3142    1]
 [3143    1]
 [3144    1]
 [3145    1]
 [3146    1]
 [3147    1]
 [3148    1]
 [3460    0]
 [3461    0]
 [3462    0]
 [3463    0]
 [3464    0]
 [3465    0]
 [3466    0]
 [3467    0]
 [3468    0]
 [3469    0]
 [3470    0]
 [3471    0]
 [3472    0]
 [3473    0]
 [3474    0]
 [3654    0]
 [3782    0]
 [3788    0]
 [3789    0]
 [3823    0]
 [3832    0]
 [3833    0]
 [3834    0]
 [3835    0]
 [3840    0]
 [3841    0]
 [3842    0]
 [3847    0]
 [3848    0]
 [3849    0]
 [3850    0]
 [3851    0]
 [3852    0]
 [3911    0]
 [3912    0]
 [3913    0]
 [3914    0]
 [3921    0]
 [3922    0]
 [3937    0]
 [3938    0]
 [3939    0]
 [3940    0]
 [3941    0]
 [3942    0]
 [3943    0]
 [3944    0]
 [3945    0]
 [3946    0]
 [3947    0]
 [3948    0]
 [3949    0]
 [3950    0]
 [3951    0]
 [3953    0]
 [3954    0]
 [3955    0]
 [3956    0]
 [3957    0]
 [3958    0]
 [3987    0]
 [3988    0]
 [3989    0]
 [4013    0]
 [4014    0]
 [4018    0]
 [4019    0]
 [4020    0]
 [4496    0]
 [4522    0]
 [4523    0]]
9/20:草鱼
[[   0    0]
 [   3    0]
 [   5    0]
 [   6    0]
 [  22    0]
 [  23    0]
 [  37    0]
 [  56    0]
 [  57    0]
 [  58    0]
 [ 108    0]
 [ 114    0]
 [ 129    0]
 [ 146    0]
 [ 148    0]
 [ 149    0]
 [ 156    0]
 [ 161    0]
 [ 207    0]
 [ 208    0]
 [ 210    0]
 [ 211    0]
 [ 212    0]
 [ 213    0]
 [ 214    0]
 [ 217    0]
 [ 272    0]
 [ 292    0]
 [ 293    0]
 [ 440    0]
 [ 442    0]
 [ 446    0]
 [ 447    0]
 [ 448    0]
 [ 453    0]
 [ 454    0]
 [ 680    0]
 [ 691    0]
 [ 693    0]
 [ 743    0]
 [ 744    0]
 [ 816    0]
 [ 817    0]
 [ 827    0]
 [ 828    0]
 [ 836    0]
 [ 856    0]
 [ 857    0]
 [ 865    0]
 [ 877    0]
 [ 878    0]
 [ 880    0]
 [ 882    0]
 [ 883    0]
 [ 884    0]
 [ 885    0]
 [ 886    0]
 [ 887    0]
 [ 888    0]
 [ 890    0]
 [ 894    0]
 [ 895    0]
 [ 910    0]
 [ 911    0]
 [ 912    0]
 [ 913    0]
 [ 914    0]
 [ 915    0]
 [ 916    0]
 [1018    0]
 [1019    1]
 [1020    0]
 [1021    0]
 [1030    0]
 [1031    0]
 [1033    0]
 [1034    0]
 [1035    0]
 [1036    0]
 [1037    0]
 [1039    0]
 [1040    0]
 [1041    0]
 [1042    0]
 [1043    0]
 [1045    0]
 [1046    0]
 [1047    0]
 [1048    0]
 [1049    0]
 [1050    0]
 [1051    0]
 [1052    0]
 [1053    0]
 [1054    0]
 [1055    0]
 [1056    0]
 [1059    0]
 [1060    0]
 [1061    0]
 [1062    0]
 [1063    0]
 [1064    0]
 [1065    0]
 [1066    0]
 [1067    0]
 [1068    0]
 [1069    0]
 [1070    0]
 [1071    0]
 [1072    0]
 [1073    0]
 [1074    0]
 [1075    0]
 [1076    0]
 [1078    0]
 [1080    0]
 [1081    0]
 [1082    0]
 [1127    0]
 [1129    0]
 [1130    0]
 [1132    0]
 [1133    0]
 [1210    0]
 [1213    1]
 [1239    1]
 [1312    1]
 [1313    1]
 [1314    1]
 [1317    1]
 [1319    1]
 [1322    0]
 [1324    0]
 [1325    0]
 [1327    0]
 [1351    0]
 [1357    0]
 [1400    0]
 [1401    0]
 [1483    0]
 [1484    0]
 [1486    0]
 [1487    0]
 [1496    0]
 [1497    0]
 [1498    0]
 [1501    0]
 [1533    0]
 [1537    0]
 [1538    0]
 [1539    0]
 [1540    0]
 [1552    0]
 [1553    0]
 [1554    0]
 [1555    0]
 [1559    0]
 [1583    0]
 [1608    0]
 [1609    0]
 [1759    0]
 [1774    1]
 [1775    1]
 [1777    1]
 [1778    1]
 [1779    1]
 [1780    1]
 [1784    1]
 [1785    1]
 [1786    1]
 [1788    1]
 [1789    0]
 [1790    1]
 [1796    1]
 [1800    0]
 [1821    0]
 [1823    0]
 [1826    0]
 [1827    0]
 [1828    0]
 [1830    0]
 [1831    0]
 [1832    0]
 [1833    0]
 [1834    0]
 [1835    0]
 [1836    0]
 [1839    0]
 [1846    1]
 [1847    1]
 [1848    1]
 [1858    0]
 [1863    1]
 [1903    0]
 [1912    0]
 [1913    0]
 [1922    1]
 [1996    1]
 [1997    1]
 [1998    1]
 [2028    0]
 [2048    1]
 [2089    0]
 [2094    0]
 [2095    0]
 [2112    0]
 [2114    0]
 [2115    0]
 [2152    0]
 [2275    0]
 [2290    0]
 [2293    0]
 [2310    0]
 [2332    0]
 [2333    0]
 [2335    0]
 [2336    0]
 [2337    1]
 [2338    1]
 [2339    1]
 [2406    0]
 [2447    0]
 [2448    0]
 [2449    0]
 [2450    0]
 [2451    0]
 [2452    0]
 [2453    0]
 [2454    0]
 [2455    0]
 [2456    0]
 [2457    0]
 [2465    0]
 [2500    1]
 [2501    1]
 [2502    1]
 [2503    1]
 [2504    0]
 [2513    0]
 [2514    0]
 [2515    0]
 [2516    1]
 [2517    1]
 [2518    0]
 [2519    0]
 [2520    1]
 [2521    0]
 [2522    0]
 [2523    0]
 [2524    0]
 [2525    0]
 [2526    0]
 [2528    1]
 [2530    0]
 [2531    1]
 [2534    1]
 [2535    1]
 [2542    1]
 [2551    0]
 [2561    0]
 [2562    0]
 [2564    1]
 [2565    1]
 [2566    1]
 [2602    0]
 [2622    0]
 [2623    0]
 [2624    0]
 [2625    0]
 [2626    0]
 [2627    0]
 [2628    0]
 [2636    0]
 [2685    0]
 [2686    0]
 [2689    0]
 [2690    0]
 [2691    0]
 [2695    0]
 [2699    0]
 [2702    0]
 [2784    0]
 [2785    0]
 [2820    0]
 [2898    0]
 [2905    0]
 [2906    0]
 [2910    1]
 [2968    0]
 [2969    0]
 [2982    0]
 [2983    0]
 [2984    0]
 [2985    0]
 [2986    0]
 [2987    0]
 [2988    0]
 [2989    0]
 [2990    0]
 [2991    0]
 [2992    0]
 [2993    0]
 [2994    0]
 [2998    0]
 [2999    0]
 [3067    1]
 [3080    0]
 [3081    0]
 [3082    0]
 [3084    0]
 [3088    0]
 [3089    0]
 [3149    1]
 [3162    0]
 [3163    0]
 [3164    0]
 [3272    1]
 [3273    1]
 [3274    1]
 [3275    0]
 [3276    1]
 [3277    1]
 [3278    1]
 [3279    1]
 [3282    0]
 [3283    1]
 [3289    1]
 [3293    0]
 [3323    0]
 [3339    0]
 [3444    0]
 [3453    0]
 [3640    0]
 [3641    0]
 [3642    0]
 [3643    0]
 [3644    0]
 [3645    0]
 [3652    0]
 [3653    0]
 [3655    0]
 [3657    0]
 [3658    0]
 [3659    0]
 [3660    0]
 [3661    0]
 [3662    0]
 [3729    0]
 [3740    0]
 [3741    0]
 [3742    0]
 [3743    0]
 [3753    1]
 [3757    1]
 [3758    1]
 [3781    0]
 [3787    0]
 [3790    0]
 [3793    0]
 [3810    0]
 [3818    1]
 [3822    1]
 [3824    1]
 [3825    1]
 [3826    1]
 [3827    1]
 [3828    1]
 [3829    1]
 [3830    0]
 [3843    1]
 [3844    1]
 [3854    0]
 [3855    0]
 [3856    1]
 [3857    0]
 [3859    0]
 [3862    0]
 [3866    0]
 [3873    0]
 [3877    0]
 [3878    0]
 [3879    0]
 [3880    0]
 [3881    0]
 [3882    0]
 [3887    0]
 [3888    0]
 [3889    0]
 [3891    0]
 [3894    0]
 [3896    0]
 [3900    0]
 [3901    0]
 [3902    0]
 [3903    0]
 [3904    0]
 [3905    0]
 [3907    0]
 [3908    0]
 [3915    0]
 [3916    0]
 [3917    0]
 [3963    0]
 [3964    0]
 [3965    0]
 [3966    0]
 [3967    0]
 [3968    0]
 [3969    0]
 [3970    0]
 [3971    0]
 [3972    0]
 [3973    0]
 [3974    0]
 [3975    0]
 [3976    0]
 [4012    0]
 [4021    0]
 [4022    1]
 [4023    1]
 [4024    1]
 [4025    1]
 [4026    1]
 [4057    0]
 [4058    0]
 [4059    0]
 [4514    0]
 [4531    0]
 [4532    0]
 [4561    0]
 [4562    0]
 [4563    0]
 [4567    0]
 [4568    0]
 [4569    0]
 [4570    0]
 [4581    0]]
10/20:蛙
[[4530    0]]
11/20:青虾
[[  24    0]
 [  30    0]
 [  31    0]
 [ 202    0]
 [ 206    0]
 [ 367    0]
 [ 368    0]
 [ 369    0]
 [ 729    0]
 [ 730    0]
 [ 731    0]
 [ 732    0]
 [ 733    0]
 [ 734    0]
 [ 735    0]
 [ 736    0]
 [ 737    0]

In [860]:
# 计算指定品种总产量
pzlist=['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','黄鳝','蛙','乌鳢']
# pzlist=['黄鳝','蛙','乌鳢']
for pz in pzlist:
    if pz+'亩产量(斤/亩)' in df.columns:
        idx1=df[pz+'亩产量(斤/亩)']>=0
        df.loc[idx1,pz+'产量']=df.loc[idx1,pz+'亩产量(斤/亩)']*df.loc[idx1,'面积_亩']

In [861]:
df_tj=df.copy()

In [84]:
# 按指定字段划分主体并统计数据
result = df_tj.groupby(['养殖经营人名称','身份证号','统一社会信用代码','联系方式','地址']).agg({
    "养殖经营人名称": "first",  # 或 "max"/"min"（如果身份证号不同，需去重逻辑）
    "联系方式": "first",
    "身份证号": "first",
    "统一社会信用代码": "first",
    "地址": "first",
    "面积_亩": "sum",
    "鳊鲂产量": "sum",
    "淡水鲈鱼产量": "sum",
    "鲫鱼产量": "sum",
    "泥鳅产量": "sum",
    "图斑编号":list
    })

In [863]:
# 按指定字段划分主体并统计数据-多个品种
result = df_tj.groupby(['养殖经营人名称','身份证号','统一社会信用代码','联系方式','地址']).agg({
    "养殖经营人名称": "first",  # 或 "max"/"min"（如果身份证号不同，需去重逻辑）
    "联系方式": "first",
    "身份证号": "first",
    "统一社会信用代码": "first",
    "地址": "first",
    "面积_亩": "sum",
    "鳊鲂产量": "sum",
    "鲫鱼产量": "sum",
    "乌鳢产量": "sum",
    "蛙产量": "sum",
    "图斑编号":list
    })

In [864]:
result['养殖品种']=''

In [865]:
for pz in pzlist:
    if pz+'产量' in result.columns:
        idx1=result[pz+'产量']>0
        result.loc[idx1,'养殖品种']+=pz+';'

In [720]:
# 大于5亩、主体清单
idx1=result['面积_亩']>=5
idx2=result['养殖品种'].str.contains(';')
idx=idx1&idx2
result1=result[idx].copy()

In [866]:
# 不筛面积主体清单
idx2=result['养殖品种'].str.contains(';')
result2=result[idx2].copy()
result2['所属乡镇']=result2['地址'].str.split('-',expand=True)[3]
len(result2)

127

In [823]:
# 不筛面积除指定品种外，其他主体清单
idx3=~result['养殖品种'].str.contains(';')
result3=result[idx3].copy()

In [576]:
# result1['所属乡镇']=result1['地址'].str.split('-',expand=True)[3]
# result2['所属乡镇']=result2['地址'].str.split('-',expand=True)[3]
# result['所属乡镇']=result['地址'].str.split('-',expand=True)[3]
# result_z['所属乡镇']=result_z['地址'].str.split('-',expand=True)[3]

In [58]:
# 主体清单导出
result2.to_excel(os.path.join("溧阳成品养殖、苗种培育七条鱼主体0718.xlsx"))

In [446]:
# 主体清单导出
result1.to_excel(os.path.join("金湖县5亩以上成品养殖四条鱼主体0707.xlsx"))
# result2.to_excel(os.path.join("金湖县不筛面积成品养殖四条鱼主体0707.xlsx"))
# 主体清单导出
# result.to_excel(os.path.join("金湖县成品养殖主体0707.xlsx"))
# result_z.to_excel(os.path.join("金湖县主体0707_总.xlsx"))

In [690]:
# 获取地址信息，并定义统计层级
address=result['地址'].str.split('-',expand=True)
address['区镇']=address[2]+'-'+address[3]
address_unq=np.unique(address[2].tolist())
# address_unq=np.unique(address['区镇'].tolist())
address_unq

array(['洪泽区', '涟水县', '淮安工业园区', '淮安经济技术开发区', '淮阴区', '清江浦区', '盱眙县', '金湖县'],
      dtype='<U9')

In [90]:
# 创建统计表
row_index=address_unq
column_index=['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','四鱼合计']
result_tj = pd.DataFrame(index=row_index, columns=column_index)

In [91]:
# 筛选统计数据
# 创建统计表
for j in address_unq:
    for i in ['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','四鱼合计']:
        if i=='四鱼合计':
            idx=result['养殖品种'].str.contains('鳊鲂')|result['养殖品种'].str.contains('鲫鱼')|result['养殖品种'].str.contains('淡水鲈鱼')|result['养殖品种'].str.contains('泥鳅')
            idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx2&idx3])
        elif i in ['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅']:
            idx=result['养殖品种'].str.contains(i)
            idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx2&idx3])

In [579]:
# 筛选统计数据-金湖
# 创建统计表
row_index=address_unq
column_index=['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','四鱼合计','黄鳝','蛙','合计']
result_tj = pd.DataFrame(index=row_index, columns=column_index)

for j in address_unq:
    for i in ['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','四鱼合计','黄鳝','蛙','合计']:
        if i == '合计':
            idx=result['养殖品种'].str.contains(';')
            idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx2&idx3])
        elif i in ['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','黄鳝','蛙']:
            idx=result['养殖品种'].str.contains(i)
            idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx2&idx3])
        elif i=='四鱼合计':
            idx=result['养殖品种'].str.contains('鳊鲂')|result['养殖品种'].str.contains('鲫鱼')|result['养殖品种'].str.contains('淡水鲈鱼')|result['养殖品种'].str.contains('泥鳅')
            idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx2&idx3])

In [363]:
# 创建统计表
row_index=address_unq
column_index=['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','四鱼合计','非四鱼合计','所有主体','不筛面积四鱼合计']
result_tj = pd.DataFrame(index=row_index, columns=column_index)

In [364]:
# 筛选统计数据
for j in address_unq:
    for i in ['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','四鱼合计','非四鱼合计','所有主体','不筛面积四鱼合计']:
        if i == '四鱼合计':
            idx=result['养殖品种'].str.contains(';')
            idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx2&idx3])
        elif i in ['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅']:
            idx=result['养殖品种'].str.contains(i)
            idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx2&idx3])
        elif i == '非四鱼合计':
            idx=~result['养殖品种'].str.contains(';')
            idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx2&idx3])
        elif i == '所有主体':
            idx3=result_z['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result_z[idx3])
        if i == '不筛面积四鱼合计':
            idx=result['养殖品种'].str.contains(';')
#             idx2=result['面积_亩']>=5
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx3])

In [824]:
# 创建统计表
row_index=address_unq
column_index=['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','黄鳝','蛙','乌鳢','合计']
result_tj = pd.DataFrame(index=row_index, columns=column_index)
# 筛选统计数据
# 创建统计表
for j in address_unq:
    for i in ['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','黄鳝','蛙','乌鳢','合计']:
        if i=='合计':
            idx=result['养殖品种'].str.contains(';')
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx3])
        elif i in ['鳊鲂','鲫鱼','淡水鲈鱼','泥鳅','黄鳝','蛙','乌鳢']:
            idx=result['养殖品种'].str.contains(i)
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx3])

In [294]:
# 创建统计表
row_index=address_unq
column_index=['黄鳝','蛙','乌鳢','合计']
result_tj = pd.DataFrame(index=row_index, columns=column_index)
# 筛选统计数据
# 创建统计表
for j in address_unq:
    for i in ['黄鳝','蛙','乌鳢','合计']:
        if i=='合计':
            idx=result['养殖品种'].str.contains(';')
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx3])
        elif i in ['黄鳝','蛙','乌鳢']:
            idx=result['养殖品种'].str.contains(i)
            idx3=result['地址'].str.contains(j)
            result_tj.loc[j,i]=len(result[idx&idx3])

In [692]:
# 统计数据导出
result_tj.to_excel(os.path.join("淮安市七鱼主体数量0721.xlsx"))

In [693]:
result_tj

            鳊鲂   鲫鱼 淡水鲈鱼 泥鳅 黄鳝  蛙 乌鳢   合计
洪泽区         17   73    1  0  0  0  0   78
涟水县          0  532    0  1  0  0  0  533
淮安工业园区       0    0    0  0  0  0  0    0
淮安经济技术开发区    0    2    0  0  0  0  0    2
淮阴区         20  205    0  4  0  0  0  212
清江浦区         1   36    1  0  0  0  0   36
盱眙县          0    0    0  0  0  0  0    0
金湖县        680  700    4  1  1  1  0  725

### 匹配信息表并导出

In [867]:
# 原始数据匹配
# ===== 参数配置 =====
output_path = "七鱼清单.xlsx"  # 输出文件路径
output_path2 = "其他清单.xlsx"  
output_path3 = "异常数据.xlsx"# 输出文件路径
df_b = result2.copy() # 匹配不同结果表格
# df_c = result.copy()# 相同用途其他
df_c = result_z.copy() # 其他所有

In [847]:
# ===== 关键词列表 =====其他所有
keywords = ["鲫鱼", "鳊鲂", "泥鳅", "鲈鱼", "黄鳝", "蛙","乌鳢"] #, "黄鳝", "蛙"
# ===== 读取数据 =====
# idx1=df_mcl['用途'].str.contains('成品养殖')|df_mcl['用途'].str.contains('苗种培育')
idx1=df_mcl['用途'].str.contains('成品养殖')
df_a = df_mcl[idx1].copy()
# df_a2 = df_mcl.copy()
# ===== 筛选 A 表中品种字段包含关键词的数据 =====
mask = df_a["养殖品种/预计亩产量"].astype(str).apply(lambda x: any(k in x for k in keywords))
filtered_a = df_a[mask].copy()

# mask2 = df_a2["养殖品种/预计亩产量"].astype(str).apply(lambda x: not any(k in x for k in keywords))
# filtered_c = df_a2[mask2].copy()
common_index = df_mcl.index.intersection(filtered_a.index)
filtered_c = df_mcl.drop(common_index)

In [417]:
# ===== 关键词列表 =====其他所有2
keywords = ["鲫鱼", "鳊鲂", "泥鳅", "鲈鱼", "黄鳝", "蛙","乌鳢"] #, "黄鳝", "蛙"
# ===== 读取数据 =====
idx1=df_mcl['用途'].str.contains('成品养殖')|df_mcl['用途'].str.contains('苗种培育')
# idx1=df_mcl['用途'].str.contains('成品养殖')
df_a = df_mcl[idx1].copy()
# df_a2 = df_mcl.copy()
# ===== 筛选 A 表中品种字段包含关键词的数据 =====
mask = df_a["养殖品种/预计亩产量"].astype(str).apply(lambda x: any(k in x for k in keywords))
filtered_a = df_a[mask].copy()
idx2 = filtered_a['用途'].str.contains('成品养殖')
idx3 = filtered_a['养殖品种/预计亩产量'].str.contains('鲫鱼')|filtered_a['养殖品种/预计亩产量'].str.contains('鳊鲂')|filtered_a['养殖品种/预计亩产量'].str.contains('鲈鱼')|filtered_a['养殖品种/预计亩产量'].str.contains('泥鳅')
idx4 = ~filtered_a['养殖品种/预计亩产量'].str.contains('黄鳝')
idx5 = ~filtered_a['养殖品种/预计亩产量'].str.contains('蛙')
idx6 = ~filtered_a['养殖品种/预计亩产量'].str.contains('乌鳢')
drop_a = filtered_a[idx2&idx3&idx4&idx5&idx6]
filtered_a = filtered_a.drop(drop_a.index)
# mask2 = df_a2["养殖品种/预计亩产量"].astype(str).apply(lambda x: not any(k in x for k in keywords))
# filtered_c = df_a2[mask2].copy()
common_index = df_mcl.index.intersection(filtered_a.index)
filtered_c = df_mcl.drop(common_index)

In [868]:
# ===== 关键词列表 =====相同用途其他
keywords = ["鲫鱼", "鳊鲂", "泥鳅", "鲈鱼", "黄鳝", "蛙","乌鳢"] #, "黄鳝", "蛙"
# ===== 读取数据 =====
idx1=df_mcl['用途'].str.contains('成品养殖')
df_a = df_mcl[idx1].copy()
# ===== 筛选 A 表中品种字段包含关键词的数据 =====
mask = df_a["养殖品种/预计亩产量"].astype(str).apply(lambda x: any(k in x for k in keywords))
filtered_a = df_a[mask].copy()

# mask2 = df_a["养殖品种/预计亩产量"].astype(str).apply(lambda x: not any(k in x for k in keywords))
# filtered_c = df_a[mask2].copy()
common_index = df_a.index.intersection(filtered_a.index)
filtered_c = df_a.drop(common_index)

In [848]:
len(filtered_a)+len(filtered_c)

12127

In [852]:
len(matched_a)+len(matched_c)

12121

In [674]:
len(matched_c)

7754

In [872]:
matched_a2["养殖品种/预计亩产量"]

253    草鱼:0.00斤/亩，鲢鱼:0.00斤/亩，鲫鱼:0.00斤/亩
254    草鱼:0.00斤/亩，鲢鱼:0.00斤/亩，鲫鱼:0.00斤/亩
255    草鱼:0.00斤/亩，鲢鱼:0.00斤/亩，鲫鱼:0.00斤/亩
615                          鲫鱼:0.00斤/亩
Name: 养殖品种/预计亩产量, dtype: object

In [869]:
matched_a,matched_a2=pipei(filtered_a,df_b,lx='七鱼')
matched_a.to_excel(output_path)
matched_a2["所在乡镇"] = matched_a2["地址"].astype(str).str.split("-").str[3]
matched_a2 = matched_a2[['养殖经营人名称', '身份证号', '统一社会信用代码', '养殖主体类型', '地址', '所在乡镇', '联系人', '联系方式',
                                   '养殖品种/预计亩产量', '图斑编号', '面积_亩','池塘所有权','池塘所有权人名称','池塘所有权人证件号码','用途']]
matched_a2.to_excel(output_path3)

In [829]:
common_index = df_mcl.index.intersection(matched_a.index)
matched_c = df_mcl.drop(common_index)
matched_c["所在乡镇"] = matched_c["地址"].astype(str).str.split("-").str[3]
matched_c = matched_c[['养殖经营人名称', '身份证号', '统一社会信用代码', '养殖主体类型', '地址', '所在乡镇', '联系人', '联系方式',
                                   '养殖品种/预计亩产量', '图斑编号', '面积_亩','池塘所有权','池塘所有权人名称','池塘所有权人证件号码','用途']]

In [871]:
matched_c,matched_c2=pipei(filtered_c,df_c,lx='其他')
# matched_c=pd.concat([matched_c,matched_a2],axis=0)
# matched_c.to_excel(output_path2)

In [174]:
def pipei(filtered,df,lx):
    filtered["match_key"] = make_key(filtered)
    df["match_key"] = make_key(df)
    # ===== 匹配：从 A 中选出匹配 B 的数据 =====
    matched_keys = set(df["match_key"])
    matched_a = filtered[filtered["match_key"].isin(matched_keys)].copy()
    matched_a2 = filtered[~filtered["match_key"].isin(matched_keys)].copy()
    # ===== 提取“乡镇”信息 =====
    matched_a["所在乡镇"] = matched_a["地址"].astype(str).str.split("-").str[3]
    if lx=='七鱼':
        matched_a["变更理由"]=''
        matched_a.drop(columns=["match_key"], inplace=True)
        matched_a = matched_a[['养殖经营人名称', '身份证号', '统一社会信用代码', '养殖主体类型', '地址', '所在乡镇', '联系人', '联系方式',
                                   '养殖品种/预计亩产量', '图斑编号', '面积_亩','池塘所有权','池塘所有权人名称','池塘所有权人证件号码','用途','变更理由']]
    else:
        matched_a.drop(columns=["match_key"], inplace=True)
        matched_a = matched_a[['养殖经营人名称', '身份证号', '统一社会信用代码', '养殖主体类型', '地址', '所在乡镇', '联系人', '联系方式',
                                   '养殖品种/预计亩产量', '图斑编号', '面积_亩','池塘所有权','池塘所有权人名称','池塘所有权人证件号码','用途']]

    return matched_a,matched_a2

In [430]:
# 按指定字段划分主体并统计数据-多个品种
result2_2 = matched_a.groupby(['养殖经营人名称','身份证号','统一社会信用代码','联系方式','地址']).agg({
    "养殖经营人名称": "first",  # 或 "max"/"min"（如果身份证号不同，需去重逻辑）
    "联系方式": "first",
    "身份证号": "first",
    "统一社会信用代码": "first",
    "地址": "first",
    "图斑编号":list,
    '养殖品种/预计亩产量':list
    })

In [431]:
result2_2['养殖品种']=result2_2['养殖品种/预计亩产量'].apply(lambda x: ','.join(map(str, x)))

In [432]:
# 创建统计表
row_index=address_unq
column_index=['鳊鲂','鲫鱼','鲈鱼','泥鳅','黄鳝','蛙','乌鳢','合计']
result_tj2 = pd.DataFrame(index=row_index, columns=column_index)
# 筛选统计数据
# 创建统计表
for j in address_unq:
    for i in ['鳊鲂','鲫鱼','鲈鱼','泥鳅','黄鳝','蛙','乌鳢','合计']:
        if i=='合计':
            idx3=result2_2['地址'].str.contains(j)
            result_tj2.loc[j,i]=len(result2_2[idx3])
        elif i in ['鳊鲂','鲫鱼','鲈鱼','泥鳅','黄鳝','蛙','乌鳢']:
            idx=result2_2['养殖品种'].str.contains(i)
            idx3=result2_2['地址'].str.contains(j)
            result_tj2.loc[j,i]=len(result2_2[idx&idx3])

In [433]:
# 统计数据导出
result_tj2.to_excel(os.path.join("高邮七鱼主体数量0720.xlsx"))
result_tj2

            鳊鲂   鲫鱼 鲈鱼 泥鳅 黄鳝  蛙 乌鳢   合计
三垛镇          0  330  9  4  0  0  4  346
临泽镇          0    2  0  0  0  0  1    3
卸甲镇          0    9  1  0  0  0  6   15
周山镇          0    2  0  0  0  0  0    2
城南经济新区（车逻镇）  1    2  0  0  0  0  4    5
汤庄镇          0    9  0  0  0  0  3   11
甘垛镇          0   90  4  8  0  0  0  102
界首镇          0    0  0  0  0  0  0    0
经济开发区（马棚街道）  1    5  0  0  0  0  0    5
菱塘回族乡        0  141  0  0  0  0  0  141
送桥镇          0    4  0  0  0  0  0    4
高邮街道         0    0  0  0  0  0  0    0
龙虬镇          0   12  1  0  0  0  0   13

In [67]:
# filtered_a["match_key"] = make_key(filtered_a)
# df_b["match_key"] = make_key(df_b)
# # ===== 匹配：从 A 中选出匹配 B 的数据 =====
# matched_keys = set(df_b["match_key"])
# matched_a = filtered_a[filtered_a["match_key"].isin(matched_keys)].copy()
# # ===== 提取“乡镇”信息 =====
# matched_a["所在乡镇"] = matched_a["地址"].astype(str).str.split("-").str[3]
# matched_a["变更理由"]=''
# # ===== 删除辅助列并保存结果 =====
# # matched_a.drop(columns=["match_key"], inplace=True)
# matched_a = matched_a[['养殖经营人名称', '身份证号', '统一社会信用代码', '养殖主体类型', '地址', '所在乡镇', '联系人', '联系方式',
#                            '养殖品种/预计亩产量', '图斑编号', '面积_亩','池塘所有权','池塘所有权人名称','池塘所有权人证件号码','用途','变更理由']]
# # matched_a=matched_a.set_index(["养殖经营人名称", "联系方式", "身份证号", "统一社会信用代码", "地址"])
# matched_a.to_excel(output_path)

In [69]:
# filtered_c["match_key"] = make_key(filtered_c)
# df_c["match_key"] = make_key(df_c)
# # ===== 匹配：从 A 中选出匹配 B 的数据 =====
# matched_keys2 = set(df_c["match_key"])
# matched_c = filtered_c[filtered_c["match_key"].isin(matched_keys2)].copy()
# # ===== 提取“乡镇”信息 =====
# matched_c["所在乡镇"] = matched_c["地址"].astype(str).str.split("-").str[3]
# # ===== 删除辅助列并保存结果 =====
# # matched_a.drop(columns=["match_key"], inplace=True)
# matched_c = matched_c[['养殖经营人名称', '身份证号', '统一社会信用代码', '养殖主体类型', '地址', '所在乡镇', '联系人', '联系方式',
#                            '养殖品种/预计亩产量', '图斑编号', '面积_亩','池塘所有权','池塘所有权人名称','池塘所有权人证件号码','用途']]
# # matched_a=matched_a.set_index(["养殖经营人名称", "联系方式", "身份证号", "统一社会信用代码", "地址"])
# matched_c.to_excel(output_path2)

### 按地址分sheet导出

In [703]:
address=matched_a['地址'].str.split('-',expand=True)
address_unq=np.unique(address[2].tolist())
address_unq1=address_unq[address_unq!='其他区域']
idx1=address[3].str.contains('其他区域')
address2=address[idx1].copy()
address_unq2=np.unique(address2[4].tolist())

address3=matched_c['地址'].str.split('-',expand=True)
address_unq3=np.unique(address3[2].tolist())

address_unq

array(['洪泽区', '涟水县', '淮安经济技术开发区', '淮阴区', '清江浦区', '金湖县'], dtype='<U9')

In [704]:
address_unq_z=list(set(list(address_unq) + list(address_unq3)))
address_unq_z

['涟水县', '金湖县', '淮阴区', '淮安生态文旅区', '淮安经济技术开发区', '清江浦区', '盱眙县', '淮安工业园区', '洪泽区']

In [146]:
with pd.ExcelWriter(output_path.replace('.xlsx','_按乡镇.xlsx')) as writer:
    for i in address_unq1:
        idx=matched_a['地址'].str.contains(i)
        matched_b=matched_a[idx].copy()
        matched_b.to_excel(writer, sheet_name=i, index=False)
    for j in address_unq2:
        idx=matched_a['地址'].str.contains(j)
        matched_b=matched_a[idx].copy()
        matched_b.to_excel(writer, sheet_name=j, index=False)

### 按地址分sheet导出-常规

In [ ]:
with pd.ExcelWriter(output_path) as writer:
    for i in address_unq:
        idx=matched_a['地址'].str.contains(i)
        matched_b=matched_a[idx].copy()
        matched_b.to_excel(writer, sheet_name=i, index=False)

### 按地址分excel导出

In [152]:
for i in address_unq1:
    idx=matched_a['地址'].str.contains(i)
    matched_b=matched_a[idx].copy()
    matched_b.to_excel(i+'.xlsx', index=False)
for j in address_unq2:
    idx=matched_a['地址'].str.contains(j)
    matched_b=matched_a[idx].copy()
    matched_b.to_excel(j+'.xlsx', index=False)

### 按地址分excel导出-常规

In [705]:
e=0
for i in address_unq_z:
    with pd.ExcelWriter(i+'.xlsx') as writer:
        idx=matched_a['地址'].str.contains(i)
        matched_a2=matched_a[idx].copy()
        e=e+len(matched_a2)
        matched_a2.to_excel(writer, sheet_name='七鱼', index=False)
        idx2=matched_c['地址'].str.contains(i)
        matched_c2=matched_c[idx2].copy()
        e=e+len(matched_c2)
        matched_c2.to_excel(writer, sheet_name='其他鱼', index=False)

In [701]:
e=0
for i in address_unq:
    with pd.ExcelWriter(i+'.xlsx') as writer:
        idx=matched_a['地址'].str.contains(i)
        matched_a2=matched_a[idx].copy()
        e=e+len(matched_a2)
        matched_a2.to_excel(writer, sheet_name='七鱼', index=False)
        idx2=matched_c['地址'].str.contains(i)
        matched_c2=matched_c[idx2].copy()
        e=e+len(matched_c2)
        matched_c2.to_excel(writer, sheet_name='其他鱼', index=False)

In [706]:
e

38080

In [42]:
i='新庄街道'
with pd.ExcelWriter(i+'.xlsx') as writer:
    idx=matched_a['地址'].str.contains(i)
    matched_a2=matched_a[idx].copy()
    e=e+len(matched_a2)
    matched_a2.to_excel(writer, sheet_name='七鱼', index=False)
    idx2=matched_c['地址'].str.contains(i)
    matched_c2=matched_c[idx2].copy()
    e=e+len(matched_c2)
    matched_c2.to_excel(writer, sheet_name='其他鱼', index=False)

In [87]:
e

31420

In [451]:
# 创建统计表
row_index=address_unq
column_index=['主体','塘口']
result_tj5 = pd.DataFrame(index=row_index, columns=column_index)

In [454]:
for j in address_unq:
    result_tj5.loc[j,'主体']=len(result2[result2['地址'].str.contains(j).copy()])
    result_tj5.loc[j,'塘口']=len(matched_a[matched_a['地址'].str.contains(j).copy()])

In [456]:
# 统计数据导出
result_tj5.to_excel(os.path.join("响水苗种培育成品养殖主体、池塘数量0717.xlsx"))

In [455]:
result_tj5

                  主体   塘口
南河镇                1    1
县开发区              13   22
双港镇               10   23
响水县滩涂开发管理局驻陈港办事处   0    0
大有镇               24   38
小尖镇               28   48
江苏兴海控股集团有限公司       0    0
江苏农垦金鲤渔业有限公司       1   15
江苏银宝盐业有限公司         0    0
省属灌东盐场            22  455
省属黄海农场            31   91
运河镇                9   42
陈家港镇               0    0
黄圩镇               13   30

In [427]:
result_a=matched_a.groupby(['养殖经营人名称','身份证号','统一社会信用代码','联系方式','地址']).agg({
    "养殖经营人名称": "first",  # 或 "max"/"min"（如果身份证号不同，需去重逻辑）
    "联系方式": "first",
    "身份证号": "first",
    "统一社会信用代码": "first",
    "地址": "first",
    "所在乡镇":"first",
    "养殖主体类型":"first",
    "鳊鲂产量": "sum",
    "淡水鲈鱼产量": "sum",
    "泥鳅产量": "sum",
    "鲫鱼产量": "sum",
    "蛙产量": "sum",
    "黄鳝产量": "sum",
    "图斑编号":list
    })

In [428]:
result_a['养殖品种']=''
# 根据产量得出养殖品种
if '鳊鲂产量' in result_a.columns:
    idx1=result_a['鳊鲂产量']>0
    result_a.loc[idx1,'养殖品种']+='鳊鲂;'
if '淡水鲈鱼产量' in result_a.columns:
    idx2=result_a['淡水鲈鱼产量']>0
    result_a.loc[idx2,'养殖品种']+='淡水鲈鱼;'
if '鲫鱼产量' in result_a.columns:
    idx3=result_a['鲫鱼产量']>0
    result_a.loc[idx3,'养殖品种']+='鲫鱼;'
if '泥鳅产量' in result_a.columns:
    idx4=result_a['泥鳅产量']>0
    result_a.loc[idx4,'养殖品种']+='泥鳅;'
if '黄鳝产量' in result_a.columns:
    idx5=result_a['黄鳝产量']>0
    result_a.loc[idx5,'养殖品种']+='黄鳝;'
if '蛙产量' in result_a.columns:
    idx6=result_a['蛙产量']>0
    result_a.loc[idx6,'养殖品种']+='蛙;'

In [429]:
result_a.to_excel(output_path.replace('.xlsx','-汇总-原.xlsx'), index=False)

### 匹配所有主体清单

In [156]:
# 原始数据匹配
# ===== 参数配置 =====
output_path = "丹阳市所有养殖主体0409清单.xlsx"  # 输出文件路径

In [198]:
# ===== 读取数据 =====
df_a = df_mcl.copy()
df_b = result_z.copy()

In [199]:
filtered_a = df_a.copy()

In [200]:
filtered_a["match_key"] = make_key(filtered_a)
df_b["match_key"] = make_key(df_b)
# ===== 匹配：从 A 中选出匹配 B 的数据 =====
matched_keys = set(df_b["match_key"])
matched_a = filtered_a[filtered_a["match_key"].isin(matched_keys)].copy()
# ===== 提取“乡镇”信息 =====
matched_a["所在乡镇"] = matched_a["地址"].astype(str).str.split("-").str[3]
# ===== 删除辅助列并保存结果 =====
matched_a.drop(columns=["match_key"], inplace=True)
matched_a = matched_a[['养殖经营人名称', '身份证号', '养殖主体类型','统一社会信用代码', '地址', '所在乡镇', '联系人', '联系方式',
                           '养殖品种/预计亩产量', '图斑编号', '面积_亩']]
matched_a.to_excel(output_path, index=False)

In [874]:
rawpath = r'E:\江苏省养殖池塘上图入库项目\填报数据统计\13个县4条鱼主体统计\7月新\各地产量为0、无图斑数据'
os.chdir(rawpath)
for i in ['宝应县','丹阳市','高邮市','淮安区','建湖县','金湖县','溧阳市','射阳县','吴江区','武进区','响水县','兴化市','宜兴市']:

    df_mcl=pd.read_excel(i+'.xlsx')
    idx2=df_mcl['图斑面积']!='/'
    idx22=df_mcl['图斑面积']=='/'
    df_mcl['面积_亩']=''
    df_mcl.loc[idx2,'面积_亩']=df_mcl.loc[idx2,'图斑面积'].astype(float)*0.0015
    df_mcl.loc[idx22,'面积_亩']='/'
    df_mcl_a = df_mcl[['养殖经营人名称', '身份证号', '统一社会信用代码', '养殖主体类型', '地址', '联系人', '联系方式',
                                   '养殖品种/预计亩产量', '图斑编号', '面积_亩','池塘所有权','池塘所有权人名称','池塘所有权人证件号码','用途']]
    df_mcl_a.to_excel(i+'_异常数据.xlsx', index=False)
# df_mcl=pd.read_excel('金湖县0409.xlsx')#,skiprows=1